const ayaya = {
  alamat: 'Jaksel gaul',
  email: 'sara@gmail.com',
  foto_diri: 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEASABIAAD',
  foto_ktp: 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD',
  id_kostan: 1,
  id_owner: 1,
  kelamin: 2,
  kota: 3101,
  nama: 'Sarasvati',
  nama_belakang: '',
  nama_depan: '',
  noktp: '21412312312312',
  notelp: '08567213912',
  pesan: 'sadasdasd',
  provinsi: 31,
  status: 1,
  tempat_kerja: '',
  tempat_pendidikan: 'UNDIP',
  umur: 21,
  active: true,
};
